// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtyDQWV-qYHuHwBXHKV3C_eae-ZkJBwdo',
    appId: '1:317403975031:web:9c3ea36a08928712b82572',
    messagingSenderId: '317403975031',
    projectId: 'billing-app-db',
    authDomain: 'billing-app-db.firebaseapp.com',
    storageBucket: 'billing-app-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFuwfMXWyBCbmpT2a2cCfSkw9wu3thihU',
    appId: '1:317403975031:android:133d4462deda069eb82572',
    messagingSenderId: '317403975031',
    projectId: 'billing-app-db',
    storageBucket: 'billing-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1TxuFMPSP47BWCeLsrmlEG_Q6rxG6ZA0',
    appId: '1:317403975031:ios:bc1f35ab0bfc1e9ab82572',
    messagingSenderId: '317403975031',
    projectId: 'billing-app-db',
    storageBucket: 'billing-app-db.firebasestorage.app',
    iosBundleId: 'com.example.invoiceBillingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1TxuFMPSP47BWCeLsrmlEG_Q6rxG6ZA0',
    appId: '1:317403975031:ios:bc1f35ab0bfc1e9ab82572',
    messagingSenderId: '317403975031',
    projectId: 'billing-app-db',
    storageBucket: 'billing-app-db.firebasestorage.app',
    iosBundleId: 'com.example.invoiceBillingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtyDQWV-qYHuHwBXHKV3C_eae-ZkJBwdo',
    appId: '1:317403975031:web:a74e257f695502b9b82572',
    messagingSenderId: '317403975031',
    projectId: 'billing-app-db',
    authDomain: 'billing-app-db.firebaseapp.com',
    storageBucket: 'billing-app-db.firebasestorage.app',
  );
}
