import 'package:invoice_billing_app/core/entities/quotation.dart';

class QuotationModel extends Quotation {
  QuotationModel({
    required super.quotationNumber,
    required super.customerName,
    required super.customerPhone,
    required super.customerAddress,
    required super.customerStateName,
    required super.customerCode,
    required super.shippingName,
    required super.shippingAddress,
    required super.shippingState,
    required super.shippingCode,
    required super.issuedDate,
    required super.validUntilDate,
    required super.products,
    required super.subTotal,
    required super.sgstPercent,
    required super.cgstPercent,
    required super.sgstAmount,
    required super.cgstAmount,
    required super.roundOff,
    required super.grandTotal,
    required super.grandTotalInWords,
    required super.termsAndConditions,
  });

  QuotationModel copyWith({
    String? quotationNumber,
    String? customerName,
    String? customerPhone,
    String? customerAddress,
    String? customerStateName,
    String? customerCode,
    String? shippingName,
    String? shippingAddress,
    String? shippingState,
    String? shippingCode,
    DateTime? issuedDate,
    DateTime? validUntilDate,
    List<Product>? products,
    double? subTotal,
    double? sgstPercent,
    double? cgstPercent,
    double? sgstAmount,
    double? cgstAmount,
    double? roundOff,
    double? grandTotal,
    String? grandTotalInWords,
    String? termsAndConditions,
  }) {
    return QuotationModel(
      quotationNumber: quotationNumber ?? this.quotationNumber,
      customerName: customerName ?? this.customerName,
      customerPhone: customerPhone ?? this.customerPhone,
      customerAddress: customerAddress ?? this.customerAddress,
      customerStateName: customerStateName ?? this.customerStateName,
      customerCode: customerCode ?? this.customerCode,
      shippingName: shippingName ?? this.shippingName,
      shippingAddress: shippingAddress ?? this.shippingAddress,
      shippingState: shippingState ?? this.shippingState,
      shippingCode: shippingCode ?? this.shippingCode,
      issuedDate: issuedDate ?? this.issuedDate,
      validUntilDate: validUntilDate ?? this.validUntilDate,
      products: products ?? this.products,
      subTotal: subTotal ?? this.subTotal,
      sgstPercent: sgstPercent ?? this.sgstPercent,
      cgstPercent: cgstPercent ?? this.cgstPercent,
      sgstAmount: sgstAmount ?? this.sgstAmount,
      cgstAmount: cgstAmount ?? this.cgstAmount,
      roundOff: roundOff ?? this.roundOff,
      grandTotal: grandTotal ?? this.grandTotal,
      grandTotalInWords: grandTotalInWords ?? this.grandTotalInWords,
      termsAndConditions: termsAndConditions ?? this.termsAndConditions,
    );
  }

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'quotationNumber': quotationNumber,
      'customerName': customerName,
      'customerPhone': customerPhone,
      'customerAddress': customerAddress,
      'issuedDate': issuedDate.millisecondsSinceEpoch,
      'validUntilDate': validUntilDate.millisecondsSinceEpoch,
      'products': products.map((x) => x.toMap()).toList(),
      'subTotal': subTotal,
      'sgstPercent': sgstPercent,
      'cgstPercent': cgstPercent,
      'sgstAmount': sgstAmount,
      'cgstAmount': cgstAmount,
      'roundOff': roundOff,
      'grandTotal': grandTotal,
      'grandTotalInWords': grandTotalInWords,
      'termsAndConditions': termsAndConditions,
      'customerStateName': customerStateName,
      'customerCode': customerCode,
      'shippingName': shippingName,
      'shippingAddress': shippingAddress,
      'shippingState': shippingState,
      'shippingCode': shippingCode,
    };
  }

  factory QuotationModel.fromEntity(Quotation quotation) {
    return QuotationModel(
      quotationNumber: quotation.quotationNumber,
      customerName: quotation.customerName,
      customerPhone: quotation.customerPhone,
      customerAddress: quotation.customerAddress,
      customerStateName: quotation.customerStateName,
      customerCode: quotation.customerCode,
      shippingName: quotation.shippingName,
      shippingAddress: quotation.shippingAddress,
      shippingState: quotation.shippingState,
      shippingCode: quotation.shippingCode,
      issuedDate: quotation.issuedDate,
      validUntilDate: quotation.validUntilDate,
      products: quotation.products,
      subTotal: quotation.subTotal,
      sgstPercent: quotation.sgstPercent,
      cgstPercent: quotation.cgstPercent,
      sgstAmount: quotation.sgstAmount,
      cgstAmount: quotation.cgstAmount,
      roundOff: quotation.roundOff,
      grandTotal: quotation.grandTotal,
      grandTotalInWords: quotation.grandTotalInWords,
      termsAndConditions: quotation.termsAndConditions,
    );
  }

  factory QuotationModel.fromMap(Map<String, dynamic> map) {
    return QuotationModel(
      quotationNumber: map['quotationNumber'] as String,
      customerName: map['customerName'] as String,
      customerPhone: map['customerPhone'] as String,
      customerAddress: map['customerAddress'] as String,
      customerStateName: map['customerStateName'] as String,
      customerCode: map['customerCode'] as String,
      shippingName: map['shippingName'] as String,
      shippingAddress: map['shippingAddress'] as String,
      shippingState: map['shippingState'] as String,
      shippingCode: map['shippingCode'] as String,
      issuedDate: DateTime.fromMillisecondsSinceEpoch(
          (map['issuedDate'] as num).toInt()),
      validUntilDate: DateTime.fromMillisecondsSinceEpoch(
          (map['validUntilDate'] as num).toInt()),
      products: List<Product>.from(
        (map['products'] as List<dynamic>).map<Product>(
          (x) => Product.fromMap(x as Map<String, dynamic>),
        ),
      ),
      subTotal: (map['subTotal'] as num).toDouble(),
      sgstPercent: (map['sgstPercent'] as num).toDouble(),
      cgstPercent: (map['cgstPercent'] as num).toDouble(),
      sgstAmount: (map['sgstAmount'] as num).toDouble(),
      cgstAmount: (map['cgstAmount'] as num).toDouble(),
      roundOff: (map['roundOff'] as num).toDouble(),
      grandTotal: (map['grandTotal'] as num).toDouble(),
      grandTotalInWords: map['grandTotalInWords'] as String,
      termsAndConditions: map['termsAndConditions'] ?? "",
    );
  }
}
